/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import GUI.Componentes.TemaPanelLateral;

/**
 *
 * @author USUARIO
 */
public class PanelLateral extends javax.swing.JPanel {

    /**
     * Creates new form PanelLateral
     */
    
    TemaPanelLateral temaPanelLateral = new TemaPanelLateral();
    
    public PanelLateral() {
        initComponents();
        aplicarTemas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelLateral = new javax.swing.JPanel();
        jLabelTipoPropiedad = new javax.swing.JLabel();
        jLabelCantidadAmbientes = new javax.swing.JLabel();
        jLabelCochera = new javax.swing.JLabel();
        jLabelSuperficie = new javax.swing.JLabel();
        jLabelAmueblado = new javax.swing.JLabel();
        jLabelCantBanios = new javax.swing.JLabel();
        jLabelZona = new javax.swing.JLabel();
        jLabelPrecio = new javax.swing.JLabel();
        jLabelFiltrosResultados = new javax.swing.JLabel();
        jTextFieldTipoPropiedad = new javax.swing.JTextField();
        jTextFieldCantAmbientes = new javax.swing.JTextField();
        jTextFieldCantBanios = new javax.swing.JTextField();
        jTextFieldZona = new javax.swing.JTextField();
        jTextFieldSuperficie = new javax.swing.JTextField();
        jCheckBoxAmueblado = new javax.swing.JCheckBox();
        jCheckBoxCochera = new javax.swing.JCheckBox();
        jLabelPrecioDesde = new javax.swing.JLabel();
        jTextFieldPrecioDesde = new javax.swing.JTextField();
        jLabelPrecioHasta = new javax.swing.JLabel();
        jTextFieldPrecioHasta = new javax.swing.JTextField();
        jLabelAplicarFiltros = new javax.swing.JLabel();

        jPanelLateral.setBackground(new java.awt.Color(0, 102, 102));
        jPanelLateral.setMinimumSize(new java.awt.Dimension(213, 635));
        jPanelLateral.setPreferredSize(new java.awt.Dimension(213, 635));
        jPanelLateral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTipoPropiedad.setText(" PROPIEDAD");
        jPanelLateral.add(jLabelTipoPropiedad, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabelCantidadAmbientes.setText("CANTIDAD DE AMBIENTES");
        jPanelLateral.add(jLabelCantidadAmbientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabelCochera.setText("COCHERA");
        jPanelLateral.add(jLabelCochera, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        jLabelSuperficie.setText("SUPERFICIE (m²)");
        jPanelLateral.add(jLabelSuperficie, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        jLabelAmueblado.setText("AMUEBLADO");
        jPanelLateral.add(jLabelAmueblado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        jLabelCantBanios.setText("CANTIDAD DE BAÑOS");
        jPanelLateral.add(jLabelCantBanios, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabelZona.setText("ZONA");
        jPanelLateral.add(jLabelZona, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jLabelPrecio.setText("PRECIO");
        jPanelLateral.add(jLabelPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, -1));

        jLabelFiltrosResultados.setText("FILTROS RESULTADOS");
        jPanelLateral.add(jLabelFiltrosResultados, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jTextFieldTipoPropiedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTipoPropiedadActionPerformed(evt);
            }
        });
        jPanelLateral.add(jTextFieldTipoPropiedad, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 130, -1));
        jPanelLateral.add(jTextFieldCantAmbientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 130, -1));
        jPanelLateral.add(jTextFieldCantBanios, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 130, -1));
        jPanelLateral.add(jTextFieldZona, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 130, -1));
        jPanelLateral.add(jTextFieldSuperficie, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 130, -1));

        jCheckBoxAmueblado.setBackground(new java.awt.Color(102, 102, 255));
        jCheckBoxAmueblado.setForeground(new java.awt.Color(255, 102, 255));
        jPanelLateral.add(jCheckBoxAmueblado, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, -1, -1));
        jPanelLateral.add(jCheckBoxCochera, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, -1, -1));

        jLabelPrecioDesde.setText("DESDE");
        jPanelLateral.add(jLabelPrecioDesde, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, -1));
        jPanelLateral.add(jTextFieldPrecioDesde, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, -1));

        jLabelPrecioHasta.setText("HASTA");
        jPanelLateral.add(jLabelPrecioHasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, -1, -1));
        jPanelLateral.add(jTextFieldPrecioHasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, -1, -1));

        jLabelAplicarFiltros.setText("APLICAR FILTROS");
        jPanelLateral.add(jLabelAplicarFiltros, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 210, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelLateral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelLateral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldTipoPropiedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTipoPropiedadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTipoPropiedadActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBoxAmueblado;
    private javax.swing.JCheckBox jCheckBoxCochera;
    private javax.swing.JLabel jLabelAmueblado;
    private javax.swing.JLabel jLabelAplicarFiltros;
    private javax.swing.JLabel jLabelCantBanios;
    private javax.swing.JLabel jLabelCantidadAmbientes;
    private javax.swing.JLabel jLabelCochera;
    private javax.swing.JLabel jLabelFiltrosResultados;
    private javax.swing.JLabel jLabelPrecio;
    private javax.swing.JLabel jLabelPrecioDesde;
    private javax.swing.JLabel jLabelPrecioHasta;
    private javax.swing.JLabel jLabelSuperficie;
    private javax.swing.JLabel jLabelTipoPropiedad;
    private javax.swing.JLabel jLabelZona;
    private javax.swing.JPanel jPanelLateral;
    private javax.swing.JTextField jTextFieldCantAmbientes;
    private javax.swing.JTextField jTextFieldCantBanios;
    private javax.swing.JTextField jTextFieldPrecioDesde;
    private javax.swing.JTextField jTextFieldPrecioHasta;
    private javax.swing.JTextField jTextFieldSuperficie;
    private javax.swing.JTextField jTextFieldTipoPropiedad;
    private javax.swing.JTextField jTextFieldZona;
    // End of variables declaration//GEN-END:variables

    public void aplicarTemas() {
        temaPanelLateral.aplicarPanel(jPanelLateral, 
                jLabelFiltrosResultados, 
                jLabelTipoPropiedad, 
                jLabelCantidadAmbientes,
                jLabelCantBanios, 
                jLabelZona, 
                jLabelSuperficie, 
                jLabelAmueblado,
                jLabelCochera,
                jLabelPrecio,
                jLabelPrecioDesde,
                jLabelPrecioHasta,
                jTextFieldTipoPropiedad,
                jTextFieldCantAmbientes,
                jTextFieldCantBanios,
                jTextFieldZona,
                jTextFieldSuperficie,
                jTextFieldPrecioDesde,
                jTextFieldPrecioHasta,
                jLabelAplicarFiltros,
                jCheckBoxAmueblado,
                jCheckBoxCochera
                );
    }
}
