
package GUI;

import GUI_VISTAS.PanelGestionPropiedad;
import GUI.Componentes.TemaPanelSuperior;
import javax.swing.JPanel;


public class PanelSuperior extends javax.swing.JPanel {

    // SE CREA UNA INSTANCIA DE LA CLASE TemaPanelSuperior
    TemaPanelSuperior temaPanelSuperior = new TemaPanelSuperior();
    
   
    public PanelSuperior() {
        initComponents();
        aplicarTemas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSuperior = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1280, 100));

        jPanelSuperior.setBackground(new java.awt.Color(51, 102, 255));
        jPanelSuperior.setPreferredSize(new java.awt.Dimension(1080, 100));
        jPanelSuperior.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/IMG/Logo.png"))); // NOI18N
        jLabel1.setText("LOGO");
        jPanelSuperior.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 19, 200, -1));

        btnBuscar.setText("boton buscar");
        jPanelSuperior.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 40, 106, 29));

        jLabelUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/IMG/Loginuser.png"))); // NOI18N
        jLabelUsuario.setText("USUARIO");
        jLabelUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelUsuarioMouseClicked(evt);
            }
        });
        jPanelSuperior.add(jLabelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 30, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelSuperior, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelSuperior, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelUsuarioMouseClicked
        PanelGestionPropiedad panelGestion = new PanelGestionPropiedad();
        panelGestion.setSize(220, 635);
        panelGestion.setLocation(0, 0);
       
        
        
    }//GEN-LAST:event_jLabelUsuarioMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPanel jPanelSuperior;
    // End of variables declaration//GEN-END:variables

    public void aplicarTemas() {
        // PARA PODER INVOCAR LOS MÉTODOS QUE CREÉ EN LA CLASE TemaPanelSuperior LLAMAR A LA INSTANCIA, PUNTO Y EL MÉTODO
        // aplicarPanel ES PUBLIC POR ESO SE PUEDE INVOCAR
        temaPanelSuperior.aplicarPanel(jPanelSuperior,btnBuscar);
        
    }
    
    public void recibePanel(JPanel panel,JPanel panel2){
        panel.removeAll();
        panel.add(panel);
        panel.revalidate();
        panel.repaint();
    }

}
