
package GUI;

import GUI.Componentes.TemaPanelSuperior;


public class PanelSuperior extends javax.swing.JPanel {

    // SE CREA UNA INSTANCIA DE LA CLASE TemaPanelSuperior
    TemaPanelSuperior temaPanelSuperior = new TemaPanelSuperior();
    
   
    public PanelSuperior() {
        initComponents();
        aplicarTemas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSuperior = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1280, 100));

        jPanelSuperior.setBackground(new java.awt.Color(51, 102, 255));
        jPanelSuperior.setPreferredSize(new java.awt.Dimension(1080, 100));
        jPanelSuperior.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/IMG/Logo.png"))); // NOI18N
        jLabel1.setText("LOGO");
        jPanelSuperior.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 19, 200, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanelSuperior.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, 283, 20));

        btnBuscar.setText("boton buscar");
        jPanelSuperior.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 50, 106, 29));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/IMG/Loginuser.png"))); // NOI18N
        jLabel4.setText("USUARIO");
        jPanelSuperior.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 40, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelSuperior, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelSuperior, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanelSuperior;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    public void aplicarTemas() {
        // PARA PODER INVOCAR LOS MÉTODOS QUE CREÉ EN LA CLASE TemaPanelSuperior LLAMAR A LA INSTANCIA, PUNTO Y EL MÉTODO
        // aplicarPanel ES PUBLIC POR ESO SE PUEDE INVOCAR
        temaPanelSuperior.aplicarPanel(jPanelSuperior,btnBuscar);
        
    }

}
