/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI_VISTAS;

import AccesoDatos.PropietarioData;
import Entidades.Propietario;
import java.awt.Color;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author crist
 */
public class GestionPropietario extends javax.swing.JPanel {
     PropietarioData propietarioData = new PropietarioData();
     Propietario propietario = new Propietario();
    DefaultTableModel modeloTablaPropietariosActivos = new DefaultTableModel() {
        public boolean isCellEditable(int fila, int columna) {
            return false;
        }
    };
    DefaultTableModel modeloTablaPropietariosInactivos = new DefaultTableModel() {
        public boolean isCellEditable(int fila, int columna) {
            return false;
        }
    };
    public GestionPropietario() {
        initComponents();
        armarCabeceraPropietariosInactivos();
        cargarTablaPropietariosInactivos();
        armarCabeceraPropietariosActivos();
        cargarTablaPropietariosActivos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldDNI = new javax.swing.JTextField();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldApellido = new javax.swing.JTextField();
        jTextFieldTelefono = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnModificar = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldDomicilio = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePropietariosInactivos = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablePropietariosActivos = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(246, 246, 246));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(200, 200, 200));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Telefono");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, 24));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Nombre");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, 24));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Apellido");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, 24));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("DNI");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Domicilio");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, 24));

        jTextFieldDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDNIActionPerformed(evt);
            }
        });
        jTextFieldDNI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldDNIKeyTyped(evt);
            }
        });
        jPanel3.add(jTextFieldDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 210, 30));

        jTextFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreActionPerformed(evt);
            }
        });
        jTextFieldNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNombreKeyTyped(evt);
            }
        });
        jPanel3.add(jTextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 210, 30));

        jTextFieldApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldApellidoActionPerformed(evt);
            }
        });
        jTextFieldApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldApellidoKeyTyped(evt);
            }
        });
        jPanel3.add(jTextFieldApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 210, 30));

        jTextFieldTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTelefonoActionPerformed(evt);
            }
        });
        jTextFieldTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldTelefonoKeyTyped(evt);
            }
        });
        jPanel3.add(jTextFieldTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 210, 30));

        jLabel6.setBackground(new java.awt.Color(76, 40, 130));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Limpiar Todo");
        jLabel6.setOpaque(true);
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 270, 50));

        btnModificar.setBackground(new java.awt.Color(51, 51, 255));
        btnModificar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(255, 255, 255));
        btnModificar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnModificar.setText(" Modificaciones");
        btnModificar.setOpaque(true);
        btnModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModificarMouseClicked(evt);
            }
        });
        jPanel3.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 270, 50));

        jLabel7.setBackground(new java.awt.Color(0, 119, 35));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Agregar Propietario");
        jLabel7.setOpaque(true);
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 270, 50));

        jTextFieldDomicilio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDomicilioActionPerformed(evt);
            }
        });
        jPanel3.add(jTextFieldDomicilio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 210, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setText("Gestion Propietario");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 230, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 270, 620));

        jPanel2.setBackground(new java.awt.Color(200, 200, 200));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Propietarios Inactivos");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, 24));

        btnEliminar.setBackground(new java.awt.Color(223, 0, 0));
        btnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnEliminar.setText("Desactivar Propietario");
        btnEliminar.setOpaque(true);
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMouseClicked(evt);
            }
        });
        jPanel2.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 690, 50));

        jTablePropietariosInactivos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTablePropietariosInactivos);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 690, 210));

        jTablePropietariosActivos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTablePropietariosActivos);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 690, 210));

        jLabel8.setBackground(new java.awt.Color(0, 119, 35));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Activar Propietario");
        jLabel8.setOpaque(true);
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, 690, 50));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Propietarios Activos");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 24));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 740, 620));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDNIActionPerformed

    private void jTextFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreActionPerformed

    private void jTextFieldApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldApellidoActionPerformed

    private void jTextFieldTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTelefonoActionPerformed

    private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseClicked
        eliminacionLogicaPropietario();
        cargarTablaPropietariosInactivos();
        cargarTablaPropietariosActivos();
    }//GEN-LAST:event_btnEliminarMouseClicked

    private void jTextFieldDomicilioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDomicilioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDomicilioActionPerformed

    private void jTextFieldNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNombreKeyTyped
        char c = evt.getKeyChar();
            if((c<'a' || c>'z')&&(c<'A' || c>'Z')) evt.consume();
            if(jTextFieldNombre.getText().length()>=15){
              evt.consume();
              Toolkit.getDefaultToolkit().beep();
           }
    }//GEN-LAST:event_jTextFieldNombreKeyTyped

    private void jTextFieldApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldApellidoKeyTyped
        char c = evt.getKeyChar();
            if((c<'a' || c>'z')&&(c<'A' || c>'Z')) evt.consume();
            if(jTextFieldApellido.getText().length()>=15){
              evt.consume();
              Toolkit.getDefaultToolkit().beep();
           }
    }//GEN-LAST:event_jTextFieldApellidoKeyTyped

    private void jTextFieldDNIKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDNIKeyTyped
          char c = evt.getKeyChar();
        if ((c < '0' || c > '9') ) {
            evt.consume(); // Evita caracteres no válidos
        }

       
        if (jTextFieldDNI.getText().length() >= 8) {
            evt.consume(); // Evita que se ingresen más de 20 caracteres
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_jTextFieldDNIKeyTyped

    private void jTextFieldTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTelefonoKeyTyped
         char c = evt.getKeyChar();
        if ((c < '0' || c > '9') ) {
            evt.consume(); // Evita caracteres no válidos
        }

       
        if (jTextFieldTelefono.getText().length() >= 11) {
            evt.consume(); 
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_jTextFieldTelefonoKeyTyped

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        activacionLogicaPropietario();
        cargarTablaPropietariosInactivos();
        cargarTablaPropietariosActivos();
        
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        agregarPropietario();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        limpiarTextFields();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void btnModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarMouseClicked
        ModificarPropietario modProp = new ModificarPropietario();
        modProp.setVisible(true);
        modProp.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnModificarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnEliminar;
    private javax.swing.JLabel btnModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTablePropietariosActivos;
    private javax.swing.JTable jTablePropietariosInactivos;
    private javax.swing.JTextField jTextFieldApellido;
    private javax.swing.JTextField jTextFieldDNI;
    private javax.swing.JTextField jTextFieldDomicilio;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldTelefono;
    // End of variables declaration//GEN-END:variables
public void armarCabeceraPropietariosActivos() {
         modeloTablaPropietariosActivos.addColumn("ID");
         modeloTablaPropietariosActivos.addColumn("Nombre");
         modeloTablaPropietariosActivos.addColumn("Apellido");
         modeloTablaPropietariosActivos.addColumn("DNI");
         modeloTablaPropietariosActivos.addColumn("Domicilio");
         modeloTablaPropietariosActivos.addColumn("Telefono");
       jTablePropietariosActivos.setModel( modeloTablaPropietariosActivos);
       
//        jTablePropiedad.sizeColumnsToFit(1);
    }
public void armarCabeceraPropietariosInactivos() {
        modeloTablaPropietariosInactivos.addColumn("ID");
        modeloTablaPropietariosInactivos.addColumn("Nombre");
        modeloTablaPropietariosInactivos.addColumn("Apellido");
        modeloTablaPropietariosInactivos.addColumn("DNI");
        modeloTablaPropietariosInactivos.addColumn("Domicilio");
        modeloTablaPropietariosInactivos.addColumn("Telefono");
       jTablePropietariosInactivos.setModel(modeloTablaPropietariosInactivos);
//        jTablePropiedad.sizeColumnsToFit(1);
    }

  public void cargarTablaPropietariosActivos(){
     borrarFilasActivos();
     
     ArrayList <Propietario>propietariosActivos = new ArrayList<>();
        for(Propietario propietarioActivo: propietarioData.listarPropietarios()){
          if(propietarioActivo.isEstadoPropietario()){
              propietariosActivos .add(propietarioActivo);
              
          }  
        }
        
          for (Propietario propietario : propietariosActivos) {
            modeloTablaPropietariosActivos.addRow(new Object[]{
                propietario.getIdPropietario(),
                propietario.getNombrePropietario(),
                propietario.getApellidoPropietario(),
                propietario.getDniPropietario(),
                propietario.getDomicilioPropietario(),
                propietario.getTelefonoPropietario()
               
            });
        }
  }
  
  public void borrarFilasActivos() {
        int f = jTablePropietariosActivos.getRowCount() - 1; // CANTIDAD DE FILAS MENOS UNO
        for (; f >= 0; f--) {
            modeloTablaPropietariosActivos.removeRow(f);
        }
    }
  
  public void cargarTablaPropietariosInactivos(){
     borrarFilasInactivos();
     
     ArrayList <Propietario>propietariosInactivos = new ArrayList<>();
        for(Propietario propietarioInactivo: propietarioData.listarPropietarios()){
          if(!propietarioInactivo.isEstadoPropietario()){
              propietariosInactivos .add(propietarioInactivo);
              
          }  
        }
        
          for (Propietario propietario : propietariosInactivos) {
            modeloTablaPropietariosInactivos.addRow(new Object[]{
                propietario.getIdPropietario(),
                propietario.getNombrePropietario(),
                propietario.getApellidoPropietario(),
                propietario.getDniPropietario(),
                propietario.getDomicilioPropietario(),
                propietario.getTelefonoPropietario()
               
            });
        }
  }
  
  public void borrarFilasInactivos() {
        int f = jTablePropietariosInactivos.getRowCount() - 1; // CANTIDAD DE FILAS MENOS UNO
        for (; f >= 0; f--) {
            modeloTablaPropietariosInactivos.removeRow(f);
        }
    }
  
   private void activacionLogicaPropietario() {
        int filaSeleccionada = jTablePropietariosInactivos.getSelectedRow();
        if (filaSeleccionada != -1) { // SI HAY UNA FILA SELECCIONADA ENTRA AL CONDICIONAL
            int idPropietario = (Integer) jTablePropietariosInactivos.getValueAt(filaSeleccionada, 0); // TRAES EL VALOR DE LA FILA SELECCIONADA
            propietarioData.cambiarEstadoPropietario(idPropietario);
        } else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una fila");
        }
    }
    
    private void eliminacionLogicaPropietario() {
        int filaSeleccionada = jTablePropietariosActivos.getSelectedRow();
        if (filaSeleccionada != -1) { // SI HAY UNA FILA SELECCIONADA ENTRA AL CONDICIONAL
            int idPropietario = (Integer) jTablePropietariosActivos.getValueAt(filaSeleccionada, 0); // TRAES EL VALOR DE LA FILA SELECCIONADA
            propietarioData.cambiarEstadoPropietario(idPropietario);
        } else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una fila");
        }

//        limpiarTextFields();
//        btnEliminar.setVisible(false);
    }
    
    private void agregarPropietario(){
        Propietario propietario = new Propietario();
        
        boolean[] propietarioRelleno ={false,false,false,false,false};
        
        try{
           
            if (validacionTextField1(jTextFieldNombre)) {
                propietario.setNombrePropietario(jTextFieldNombre.getText());
                propietarioRelleno[0] = true;
            } else {
                JOptionPane.showMessageDialog(this, "Debe ingresar Nombre Propietario");
                propietarioRelleno[0] = false;
            }
            
             if (validacionTextField1(jTextFieldApellido)) {
                propietario.setApellidoPropietario(jTextFieldApellido.getText());
                propietarioRelleno[1] = true;
            } else {
                JOptionPane.showMessageDialog(this, "Debe ingresar Apellido Propietario");
                propietarioRelleno[1] = false;
            }
           
             if (validacionTextField1(jTextFieldDNI)) {
                propietario.setDniPropietario(Integer.parseInt(jTextFieldDNI.getText()));
                propietarioRelleno[2] = true;
            } else {
                JOptionPane.showMessageDialog(this, "Debe ingresar DNI");
                propietarioRelleno[2] = false;
            }
             
            if (validacionTextField1(jTextFieldDomicilio)) {
                propietario.setDomicilioPropietario(jTextFieldDomicilio.getText());
                propietarioRelleno[3] = true;
            } else {
                JOptionPane.showMessageDialog(this, "Debe ingresar Domicilio Propietario");
                propietarioRelleno[3] = false;
            }
            
            if (validacionTextField1(jTextFieldTelefono)) {
                propietario.setTelefonoPropietario(Integer.parseInt(jTextFieldTelefono.getText()));
                propietarioRelleno[4] = true;
            } else {
                JOptionPane.showMessageDialog(this, "Debe ingresar un Telefono Propietario");
               propietarioRelleno[4] = false;
            }
            
            propietario.setEstadoPropietario(true);
            
            if(propietarioRelleno[0] == true
             &&propietarioRelleno[1] == true
             &&propietarioRelleno[2] == true
             &&propietarioRelleno[3] == true
             &&propietarioRelleno[4] == true ){
             propietarioData.guardarPropietario(propietario);
            }
            
        }catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Ingrese el Dni correctamente");
            jTextFieldDNI.setText("");
            validacionTextField1(jTextFieldDNI);

        } finally {
            cargarTablaPropietariosActivos();
            limpiarTextFields();
        }
    }
    
    private boolean validacionTextField1(JTextField jtf) {
        if (jtf.getText().isEmpty()) {
            jtf.setBorder(BorderFactory.createLineBorder(Color.decode("#aa4356")));
            return false;
        } else {
            jtf.setBorder(null);
            return true;
        }
    }
    
     private boolean validacionComboBox(JComboBox cbx) {
        if (cbx.getSelectedItem().equals("-")) {
            cbx.setBorder(BorderFactory.createLineBorder(Color.decode("#aa4356")));
            return false;
        } else {
            cbx.setBorder(null);
            return true;
        }
    }
     
      private void limpiarTextFields() {
        jTextFieldNombre.setText("");
        jTextFieldApellido.setText("");
        jTextFieldDNI.setText("");
        jTextFieldDomicilio.setText("");
        jTextFieldTelefono.setText("");
        
    }
}

